name: CI 

on:
  workflow_call:
    inputs:
      event_name:
        type: string
        required: true

jobs:
  PR-title-check:
    if: inputs.event_name == 'opened' || inputs.event_name == 'reopened' || inputs.event_name == 'synchronize' || inputs.event_name == 'edited'
    uses: cyberlabrs/fornul_pipelines/.github/workflows/pr-title.yml@main
  
  Docker-build-test:
    if: inputs.event_name == 'opened' || inputs.event_name == 'reopened' || inputs.event_name == 'synchronize' || inputs.event_name == 'edited'
    uses: cyberlabrs/fornul_pipelines/.github/workflows/docker-build.yml@main
