name: CI 

on:
  workflow_call:
    inputs:
      event_name:
        type: string
        required: true
    secrets:
      node-auth-token:
        required: true

jobs:
  PR-title-check:
    uses: cyberlabrs/fornul_pipelines/.github/workflows/pr-title.yml@1.0.1
  
  Build-test:
    uses: cyberlabrs/fornul_pipelines/.github/workflows/docker-build.yml@main
    secrets:
      node-auth-token: ${{secrets.node-auth-token}}
