name: Conventional commits

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  build:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gentleseal/action-conventional-commits@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-commit-types: >
            [
              "feat",
              "fix",
              "bugs",
              "docs"
            ]
