name: Docker build 

on: 
  workflow_call:
     inputs:
      service_name:
        type: string
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      env:
        SERVICE_NAME: ${{ inputs.service_name}}
      run: |
        docker build -t test $SERVICE_NAME/.
