name: Docker build 

on: 
  workflow_call:
    secrets:
      node-auth-token:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      env:
        NODE_AUTH_TOKEN: ${{secrets.node-auth-token}}
      run: |
        docker build -t test --build-arg NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN .
