name: PR label check 

on:
  workflow_call:
    secrets: 
      repo_token:
        required: true

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check labels
        run: |
          labels=$(jq --raw-output '.pull_request.labels[] | .name' "$GITHUB_EVENT_PATH")
          if [[ $labels =~ ^(no_release|version:minor|version:major|version:patch)$ ]]; then
            echo "Exactly one label is selected."
          else
            echo "Error: You need to select exactly one label."
            exit 1
          fi

  comment:
    needs: label-check
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a pull request on main branch, you have to choose exactly one label.'
