name: 'PR Title Checker'

on: workflow_call

jobs:
  PR-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@v1.0.0
        with:
          regex: '^((f(eat|ix)|bug)|docs)/INAPP\-[1-9].+' 
          allowed_prefixes: 'feat,fix,bug,docs' 
          prefix_case_sensitive: true
          min_length: 10 
          max_length: 80 