name: PR Title Checker

on: workflow_call

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request title check
        run: |
          pull_request_title="${{ github.event.pull_request.title }}"

          if [[ $pull_request_title =~ ^(fix|feat|bug|docs)\/FORNUL-[1-9].+ ]]; then
            echo "Pull request title is in the correct format"
          else
            echo "Pull request title is not in the correct format: '<type>/FORNUL-<number>' "
            exit 1
          fi
