name: PR Title Checker

on: workflow_call

jobs:
  PR-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^((f(eat|ix)|bug)|docs)/INAPP\-[1-9].+' 
          allowed_prefixes: 'feat,fix,bug,docs' 
          prefix_case_sensitive: true
          min_length: 10
          max_length: 80
          github_token: ${{ github.token }}
     