on: 
  workflow_call:

jobs:
  set-default-label:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add label to pull request
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d "{\"labels\":[\"version:patch\"]}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"
